# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Drzewiecki - Nagrobki"
theme = "syna"
enableGitInfo = true
version = "0.17.3"

# Google Analytics tracking
googleAnalytics = ""

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "Firma Nagrobkowa Sebastian Drzewiecki"
  description = "Open Source Theme for your next project"

  [params.style]
    background = "light"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  identifier = "oferta"
  url = "/oferta"
  name = "Nasza oferta"
  weight = 20

[[menu.main]]
  identifier = "realizacje"
  url = ""
  name = "Nasze realizacje"
  weight = 30

[[menu.main]]
  identifier = "realizacje-pojedyncze"
  url = "/realizacje-pojedyncze"
  name = "Nagrobki pojedyńcze"
  weight = 10
  parent = "realizacje"

[[menu.main]]
  identifier = "realizacje-podwojne"
  url = "/realizacje-podwojne"
  name = "Nagrobki podwójne"
  weight = 20
  parent = "realizacje"

[[menu.main]]
  identifier = "realizacje-grobowce"
  url = "/realizacje-grobowce"
  name = "Grobowce"
  weight = 30
  parent = "realizacje"

[[menu.main]]
  identifier = "realizacje-dzieciece"
  url = "/realizacje-dzieciece"
  name = "Nagrobki dziecięce"
  weight = 40
  parent = "realizacje"

[[menu.main]]
  identifier = "brukarstwo"
  url = "/brukarstwo"
  name = "Brukarstwo"
  weight = 50
  parent = "realizacje"

[[menu.main]]
  identifier = "banie"
  url = "/oddzial-banie"
  name = "Oddział Banie"
  weight = 40

[[menu.main]]
  identifier = "kontakt"
  url = "/kontakt"
  name = "Kontakt"
  weight = 50

[[menu.footer]]
  url = "#"
  name = "Link"
  weight = 10

[[menu.footer]]
  url = "#"
  name = "Long Link"
  weight = 30

[[menu.footer]]
  url = "#"
  name = "Tiny Link"
  weight = 30

[[menu.copyright_footer]]
  url = "/oferta"
  name = "Nasza oferta"
  weight = 10

[[menu.copyright_footer]]
  url = "realizacje"
  name = "Nasze realizacje"
  weight = 30

[[menu.footer_social]]
  weight = 20
  name = "facebook"
  pre = "fab fa-facebook-f"
  url = "#"

[[menu.footer_social]]
  weight = 30
  name = "linkedin"
  pre = "fab fa-linkedin-in"
  url = "#"
